//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Lesson9-输入配置文件生产CSharp代码/Lesson9Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Lesson9Input: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Lesson9Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Lesson9Input"",
    ""maps"": [
        {
            ""name"": ""Action1"",
            ""id"": ""20979c75-ff03-4370-a3ab-86c9644745aa"",
            ""actions"": [
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""20ceeda5-5a00-4151-b035-12073830f4fe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""4899d9f5-4948-4a85-b7f1-5d9e4395aafb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8472497c-c8d7-46ef-b480-237bb4848e67"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""36b1da69-62c8-422b-8871-fc27643c8292"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cb2eebde-63b6-4a51-9dc2-e816dae624d3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""07874f3d-8636-485f-aa31-ab14bfa75f84"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b66ed233-9a97-4d66-9a07-f52793ec8980"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f90bbb9d-ac9d-45eb-9933-840f5fdde69e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Action2"",
            ""id"": ""8dd737b8-a163-402f-a6c9-53019ecfb022"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""5cb757dd-9ad2-4aba-8ddf-ceacc9f70860"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8a33dec1-c155-4707-b2c3-5f096b9f8459"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Action1
        m_Action1 = asset.FindActionMap("Action1", throwIfNotFound: true);
        m_Action1_Fire = m_Action1.FindAction("Fire", throwIfNotFound: true);
        m_Action1_Move = m_Action1.FindAction("Move", throwIfNotFound: true);
        // Action2
        m_Action2 = asset.FindActionMap("Action2", throwIfNotFound: true);
        m_Action2_Jump = m_Action2.FindAction("Jump", throwIfNotFound: true);
    }

    ~@Lesson9Input()
    {
        UnityEngine.Debug.Assert(!m_Action1.enabled, "This will cause a leak and performance issues, Lesson9Input.Action1.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Action2.enabled, "This will cause a leak and performance issues, Lesson9Input.Action2.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Action1
    private readonly InputActionMap m_Action1;
    private List<IAction1Actions> m_Action1ActionsCallbackInterfaces = new List<IAction1Actions>();
    private readonly InputAction m_Action1_Fire;
    private readonly InputAction m_Action1_Move;
    public struct Action1Actions
    {
        private @Lesson9Input m_Wrapper;
        public Action1Actions(@Lesson9Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fire => m_Wrapper.m_Action1_Fire;
        public InputAction @Move => m_Wrapper.m_Action1_Move;
        public InputActionMap Get() { return m_Wrapper.m_Action1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Action1Actions set) { return set.Get(); }
        public void AddCallbacks(IAction1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Action1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Action1ActionsCallbackInterfaces.Add(instance);
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IAction1Actions instance)
        {
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IAction1Actions instance)
        {
            if (m_Wrapper.m_Action1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAction1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Action1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Action1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Action1Actions @Action1 => new Action1Actions(this);

    // Action2
    private readonly InputActionMap m_Action2;
    private List<IAction2Actions> m_Action2ActionsCallbackInterfaces = new List<IAction2Actions>();
    private readonly InputAction m_Action2_Jump;
    public struct Action2Actions
    {
        private @Lesson9Input m_Wrapper;
        public Action2Actions(@Lesson9Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Action2_Jump;
        public InputActionMap Get() { return m_Wrapper.m_Action2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Action2Actions set) { return set.Get(); }
        public void AddCallbacks(IAction2Actions instance)
        {
            if (instance == null || m_Wrapper.m_Action2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Action2ActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        private void UnregisterCallbacks(IAction2Actions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        public void RemoveCallbacks(IAction2Actions instance)
        {
            if (m_Wrapper.m_Action2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAction2Actions instance)
        {
            foreach (var item in m_Wrapper.m_Action2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Action2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Action2Actions @Action2 => new Action2Actions(this);
    public interface IAction1Actions
    {
        void OnFire(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IAction2Actions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
